### ISSUE TITLE
ModuleNotFoundError: No module named 'autologging'

### ISSUE THREAD

**Issue by abrasion66** [FrodeSolheim/fs-uae-launcher#106]
I have totally removed fs-uae-launcher clone and redone it from scratch (Git clone), then done ./bootstrap && make.
When i try to launch it ( ./fs-uae-launcher ) that give me :
setup_python_path
sys.path = ['/mnt/FLESH/fs-uae-launcher', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/usr/lib/python3.9/site-packages']
Traceback (most recent call last):
  File "/mnt/FLESH/fs-uae-launcher/./fs-uae-launcher", line 7, in <module>
    from launcher.main import main
  File "/mnt/FLESH/fs-uae-launcher/launcher/main.py", line 87, in <module>
    from launcher.system.tools.updater import Updater
  File "/mnt/FLESH/fs-uae-launcher/launcher/system/tools/updater.py", line 9, in <module>
    from launcher.system.prefs.update import UpdatePrefs
  File "/mnt/FLESH/fs-uae-launcher/launcher/system/prefs/update.py", line 4, in <module>
    from launcher.system.classes.windowcache import WindowCache
  File "/mnt/FLESH/fs-uae-launcher/launcher/system/classes/windowcache.py", line 4, in <module>
    from autologging import traced
ModuleNotFoundError: No module named 'autologging'

**Comment by FrodeSolheim** [comment]
You need to install additional Python dependencies `autologging` and `rx`, for example with pip or your package manager.

Or, you can use `pipenv` to install all required dependencies locally for this project: `pipenv install` and then `pipenv run ./fs-uae-launcher` (or `pipenv shell` and then run `./fs-uae-launcher` from within that environment). This is what I'm doing now, and the `Pipfile` will be kept updated with the correct dependencies.

**Comment by abrasion66** [comment]
Well, again you solved the problem, but after that when i tried to start a game he told me that fs-uae can not be find so i made a copy of fs-uae directory in fs-uae-launcher directory but now there's an over problem :+1: 
Task: RunnerTask
Error: PermissionError
Message: [Errno 13] Permission non accordée: '/mnt/FLESH/fs-uae-launcher/fs-uae'

**Comment by FrodeSolheim** [comment]
You should put the fs-uae directory side by side with fs-uae-launcher.

**Comment by abrasion66** [comment]
if i do that he cant find fs-uae

**Comment by FrodeSolheim** [comment]
`./fs-uae-launcher` will try to find `../fs-uae/fs-uae`. Remember to compile fs-uae...

**Comment by abrasion66** [comment]
Find executable: fs-uae
- Find executable in plugins dir
  Check executable /home/abrasionux/FS-UAE/System/FS-UAE/Linux/x86-64/fs-uae: NO
  Looking in legacy plugin directories
  Check executable /home/abrasionux/FS-UAE/Plugins/FS-UAE/Linux/x86-64/fs-uae: NO
  Check executable /home/abrasionux/FS-UAE/Data/Plugins/FS-UAE/Linux/x86-64/fs-uae: NO
- Find executable side-by-side
  Check executable /mnt/FLESH/fs-uae-launcher/fs-uae: NO
- Find executable in side-by-side plugin
  Not running in a plugin
-> None
<Task "RunnerTask"> failed "Could not find emulator 'fs-uae'"

fs-uae is uptodate and compiled and work if i start it

**Comment by FrodeSolheim** [comment]
Ah, right, it used to check the presence of `setup.py` to determince if it should run in "development mode", but setup.py is gone now. I've pushed a commit which makes it check for `pyproject.toml` instead, so pull down the latest commit and it should work.

**Comment by abrasion66** [comment]
Yes ! all is done you know your stuff !
