### ISSUE TITLE
fs-uae-arcade source tarball ships empty README file

### ISSUE THREAD

**Issue by glaubitz** [FrodeSolheim/fs-uae-launcher#119]
I'm currently creating new Debian packages for `fs-uae-arcade` and `fs-uae-launcher` after splitting both from the `fs-uae` main package in Debian.

While doing that, I also ran `lintian` which is reporting some issue with the source tarball, one is an empty `README` file that should probably just be removed.

`W: fs-uae-arcade: zero-byte-file-in-doc-directory usr/share/doc/fs-uae-arcade/README`

**Comment by FrodeSolheim** [comment]
Should be fixed in the latest tarball :)
