### ISSUE TITLE
fs-uae-arcade source tarball ships binary DLL files

### ISSUE THREAD

**Issue by glaubitz** [FrodeSolheim/fs-uae-launcher#120]
I'm currently creating new Debian packages for `fs-uae-arcade` and `fs-uae-launcher` after splitting both from the `fs-uae` main package in Debian.

While doing that, I also ran `lintian` which is reporting some issue with the source tarball, one issue are the binary DLL files shipped in the original tarball which are problematic when submitting the package to Debian due to the Debian Free Software Guidelines (DFSG):

```
W: fs-uae-arcade source: source-contains-prebuilt-windows-binary OpenGL/DLLS/glut32.dll
W: fs-uae-arcade source: source-contains-prebuilt-windows-binary OpenGL/DLLS/glut64.dll
W: fs-uae-arcade source: source-contains-prebuilt-windows-binary OpenGL/DLLS/opengle32.vc7.dll
W: fs-uae-arcade source: source-contains-prebuilt-windows-binary OpenGL/DLLS/opengle32.vc9.dll
W: fs-uae-arcade source: source-contains-prebuilt-windows-binary OpenGL/DLLS/opengle64.vc9.dll
```

If the files cannot be removed from the upstream tarball, I will have to repackage the upstream tarball with the DLL files removed which I would like to avoid.

**Comment by FrodeSolheim** [comment]
I'm removing PyOpenGL ("OpenGL") directory from the source. Packagers must then depend on the operating system python3-opengl package (or similar).

**Comment by glaubitz** [comment]
I think you can just encode this into the `requires` variable of `setup.py`, can't you?

**Comment by FrodeSolheim** [comment]
I suppose. Will Debian packaging tools automatically pick that up perhaps? Something to consider for later at least.

For now, I've created new tarballs for fs-uae-launcher and fs-uae-arcade: https://fs-uae.net/download#source (Note: .tar.xz instead of .tar.gz now).

Please let me know if there are issues with these tarballs.
