### ISSUE TITLE
Language Files

### ISSUE THREAD

**Issue by cyberpunkbln** [FrodeSolheim/fs-uae-launcher#124]
Hello,

a short questions to the language files for the launcher. I have downloaded the latest stable versions and my portable file structure, then i have deleted all 3.0.5 downloaded versions and noticed that the launcher doesn't have language files.

Please can you put the language files into the packages or made an lang-pack-file?

thx

**Comment by FrodeSolheim** [comment]
Ah, is this FS-UAE Launcher 3.1.x? Have I forgot to include the translations? If so, I'll add them back.

**Comment by cyberpunkbln** [comment]
Hi,
yes the latest stable 3.1.x release without the data folder.

**Comment by FrodeSolheim** [comment]
I've posted new builds with translations:  FS-UAE 3.1.48 and FS-UAE Launcher 3.1.43 (https://fs-uae.net/download). Thanks for the bug report :)
