### ISSUE TITLE
CFBundleIdentifier (bundleID) is blank (invalid)

### ISSUE THREAD

**Issue by luckman212** [FrodeSolheim/fs-uae-launcher#141]
In FS-UAE Launcher, the `CFBundleIdentifier` (bundleID) is blank/empty. 

![](https://content.invisioncic.com/r229491/monthly_2022_01/538248081_CleanShot2022-01-19at09_21_17.thumb.png.d97ea8abe60fcb82d0a27c6f7f82dae3.png)

This is invalid and is causing a small issue on my system. Hoping that in a future version, this can be corrected?

I suggest for a BundleID, something like: `com.FrodeSolheim.FSUAELauncher`

_reference: https://www.alfredforum.com/topic/17603-wrong-icon-shown-in-the-web-search-object/#comment-92363_

**Comment by FrodeSolheim** [comment]
Fixed in 07739bb813a191cfba4c014525cc1a9865668baf (new builds on the way)

**Comment by FrodeSolheim** [comment]
FS-UAE Launcher 3.1.68 is available for download now :)
