### ISSUE TITLE
Base dir only accept ascii

### ISSUE THREAD

**Issue by vincent-lhote** [FrodeSolheim/fs-uae-launcher#21]
If I put non ascii characters in ~/.config/fs-uae/base-dir or after the --base-dir option, the program fails with a:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 25: ordinal not in range(128).

I expect to be able to use any characters. My system encoding is utf8, I should be able to put any of its character in the path (for detail, one of the character is a É).

**Comment by FrodeSolheim** [comment]
Hi, are you using the "stable" or "devel" version? If the former, can you try with the latest development version?

**Comment by FrodeSolheim** [comment]
I have not been able to reproduce this problem with the development version. Closing the issue due to lack of feedback.
