### ISSUE TITLE
(2.7.8-dev) GameListSelector label does not update after FileScanner thread has run

### ISSUE THREAD

**Issue by apiraino** [FrodeSolheim/fs-uae-launcher#33]
Hi Frode,

I've installed fs-uae-launcher and I like it very much. While learning how it works I also discovered a couple of bugs that I could help fixing (as my time allows).

First bug, here's how to reproduce:
- Select `Games` from GameListSelector dropdown, the list correctly now shows only games
- Run `Update File Database` (triggers FileScanner thread)
- **bug** when the thread finished, in the list I see Games and Configs while the GameListSelector label does not change
- `LauncherSettings.get("game_list_uuid")` returns empty

The expected behaviour is either one of these two:
- The GameListSelector label changes to `Configs and Games`

or

- The list keeps on showing the content according the GameListSelector label

I'm working on a patch for this, but first I'd like to understand which the intended behaviour is; could you give me a hint?

Thanks,
Antonio

**Comment by FrodeSolheim** [comment]
Hi, thanks for helping out!

The desired behavior is: The list keeps on showing the content according the GameListSelector label

**Comment by apiraino** [comment]
Hi @FrodeSolheim did you have time check my two pr?
https://github.com/FrodeSolheim/fs-uae-launcher/pulls

Just a head up on whether I'm on the right track or not, I may be missing something from a codebase I'm not familiar with.

Thanks,
Antonio

**Comment by FrodeSolheim** [comment]
Hi, I've just got back after being away for a few days, so I haven't been able to look at it yet. I will though :)

**Comment by FrodeSolheim** [comment]
Should be fixed by https://github.com/FrodeSolheim/fs-uae-launcher/commit/fea5a1e220e0eb2f810c5194123a6fca76cce911
