### ISSUE TITLE
six/ directory causes trouble on Arch Linux

### ISSUE THREAD

**Issue by solskogen** [FrodeSolheim/fs-uae-launcher#43]
And removing it seems to do the trick. With it, this happens:

ImportError: The 'six.moves' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

If I just remove the six/ directory, it works like a charm.

**Comment by FrodeSolheim** [comment]
Hi, is the problem with an FS-UAE package from AUR? If so, I may not be able to help, could be a packaging problem...

**Comment by solskogen** [comment]
No, this is if I compile it without the help of AUR.
But I see in the git log that you've fixed it now. So you can just go ahead
and close this :)

**Comment by FrodeSolheim** [comment]
:)
