### ISSUE TITLE
`async` keyword in Python 3.7

### ISSUE THREAD

**Issue by musuruan** [FrodeSolheim/fs-uae-launcher#62]
Hi!
In Python 3.7, `async ` became a keyword and fs-uae-launcher no longer compiles:
http://koji.rpmfusion.org/kojifiles/work/tasks/2874/232874/build.log

Downstream bug report:
https://bugzilla.rpmfusion.org/show_bug.cgi?id=4966

**Comment by hroncok** [comment]
See https://github.com/mcfletch/pyopengl/issues/14

**Comment by 5schatten** [comment]
Well any news about this issue?

**Comment by FrodeSolheim** [comment]
This has been fixed for a long time now, so closing.

(As a sidenote, the embedded PyOpenGL will be removed from the master branch soon).
