### ISSUE TITLE
compressed kickstart support

### ISSUE THREAD

**Issue by andrea-petrucci-1975** [FrodeSolheim/fs-uae-launcher#71]
please add compressed kickstart support

**Comment by FrodeSolheim** [comment]
I'm quite sure that should work in general; kickstarts can reside within archives, and FS-UAE Launcher should still find it and extract it on demand before starting FS-UAE. What particular use case does not work for you?

**Comment by andrea-petrucci-1975** [comment]
my mistake
now works
