### ISSUE TITLE
Launcher crashes on startup in KDE with error malloc_consolidate(): invalid chunk size

### ISSUE THREAD

**Issue by redpiller** [FrodeSolheim/fs-uae-launcher#75]
Now i'm sorry in advance for probably missing something obvious but as soon as i startup the the launcher from command line, i get [this](https://pastebin.com/hrhChzPZ)

**Comment by FrodeSolheim** [comment]
Version 3.1.0dev... are you running from the master branch in git? Please add more information about how you are running it, and on what distribution...

**Comment by redpiller** [comment]
Hey there, really sorry for the late reply, was on my holiday trip and then the hell broke loose... anyway: 

yes it was the master branch.
i'm using Debian buster (up to date), python 3,7 64bit (see output)
i tried the current code from git again yesterday, also i downloaded the missing "lhafile" python package from pip (python 3) and this is what i'm getting now with the current code:

the file described in the output (/home/username/Documents/FS-UAE/Cache/Logs/fs-uae-launcher.log.txt) is empty but i get the following console output:

> [LOGGING] Logging to /home/username/Documents/FS-UAE/Cache/Logs/fs-uae-launcher.log.txt
FS-UAE Launcher 3.1.0dev
['./fs-uae-launcher']
uname_result(system='Linux', node='computer', release='4.19.0-8-amd64', version='#1 SMP Debian 4.19.98-1 (2020-01-26)', machine='x86_64', processor='')
[SETTINGS] No settings path specified
[SETTINGS] Using default /home/username/Documents/FS-UAE/Data/Settings.ini
[SETTINGS] File /home/username/Documents/FS-UAE/Data/Settings.ini does not exist
[I18N] Initialize_locale language = 
[I18N] Locale is en_US
[I18N] Checking /home/username/devel/git/fs-uae-launcher/share/fs-uae-launcher/share-dir
[I18N] bindtextdomain fs-uae-launcher: /home/username/devel/git/fs-uae-launcher/share/locale
[I18N] find translations for en_US in local directory /home/username/devel/git/fs-uae-launcher/share/locale
[I18N] Path to mo file: None
[I18N] Translations object: <gettext.NullTranslations object at 0x7fee6d27ef28>
malloc_consolidate(): invalid chunk size
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = python3.7 path = /usr/bin pid = 4179
KCrash: Arguments: 
Alarm clock

**Comment by FrodeSolheim** [comment]
I did not initially succeed to reproduce this with Debian 10, but I have gotten a couple of other similar reports, and the logs all mention kCrash. So I decided to test this in the KDE desktop in Debian 10, and voila: I get the same error.

I haven't debugged any further yet, but the main suspicion is that the crash is triggered by a Qt/KDE style (or at least that the Qt style somehow influences whether the app crashes or not). Could be something else in the KDE environment which influences this as well.

**Comment by FrodeSolheim** [comment]
The following patch seems to fix it:

diff --git a/fsui/qt/qt.py b/fsui/qt/qt.py
index 6451cd9..9fae054 100644
--- a/fsui/qt/qt.py
+++ b/fsui/qt/qt.py
@@ -76,7 +76,7 @@ def init_qt():
     # fix_qt_for_maverick()
 
     fsbc.desktop.set_open_url_in_browser_function(open_url_in_browser)
-    qapplication = QtBaseApplication([])
+    qapplication = QtBaseApplication(sys.argv)
     initialize_qt_style(qapplication)
     return qapplication

**Comment by FrodeSolheim** [comment]
Doing a 3.0.3 release now (for Linux) with this fix.

**Comment by redpiller** [comment]
so they changed the ABI at some point ?

**Comment by FrodeSolheim** [comment]
Not sure. I found some documentation (at least for the C++ version of Qt) that said that QApplication must get at least one argument. So perhaps Launcher always has had a bug in that regard. However, it has always worked for me, and still does - when not running under KDE. Probably triggered by some Qt module that gets loaded in a full KDE environment.

So again, the bug was probably with the Launcher, but for some reason it has worked everywhere, except "recently" when running under KDE...

**Comment by FrodeSolheim** [comment]
> QApplication::QApplication(int &argc, char **argv)
> 
> Initializes the window system and constructs an application object with argc command line arguments in argv.
> 
> Warning: The data referred to by argc and argv must stay valid for the entire lifetime of the QApplication object. In addition, argc must be greater than zero and argv must contain at least one valid character string.

https://doc.qt.io/qt-5/qapplication.html

**Comment by redpiller** [comment]
That explains it, weird indeed,
thank you for handling this problem so fast

**Comment by thomas-w-holleis** [comment]
Just a small addition.

The requirement that the **argv** must be valid filled is not Qt specific.
By convention **argv** of an main function always contains at least one string which is the name of the called program.
Many applications rely on than.

https://opensource.com/article/19/5/how-write-good-c-main-function

Thanks for the great Amiga emulator!
