### ISSUE TITLE
since few master branch update i'm unable to launch adf/whd with the launcher

### ISSUE THREAD

**Issue by abrasion66** [FrodeSolheim/fs-uae-launcher#95]
Each time i'm using the launcher i have :

Task: RunnerTask
Error: LookupError
Message: Cannot find resource 'amiga/adf_save_disk.dat'

and when i remove the "include save disk feature" i have :

Task: RunnerTask
Error: Exception
Message: Written SHA-1 (c39bd9094d4e5f4e28c1411f3086950406062e87) does not match expected SHA-1 (891e9a547772fe0c6c19b610baf8bc4ea7fcb785)

reported SHA-1 is always the same for all adf or whd

--- Manjaro linux (Arch based distro)

**Comment by FrodeSolheim** [comment]
This was fixed in the commit 90b175b23b90535847aa09e6b5210d33909324f3 yesterday evening :)

**Comment by abrasion66** [comment]
i did a git fetch then make and didn't worked, so i recloned the repo and that work fine now. I don't ready know much about git and what i did wrong

**Comment by FrodeSolheim** [comment]
`git fetch` only syncs the remote repository data, it does not merge the upstream changes into your locally checkout branch.

Instead, use `git pull` (which is roughly the same as running `git fetch` followed by `git merge origin/master`)

**Comment by abrasion66** [comment]
guru meditation ------ 
thank you for the lesson i'm a... that work fine now with pull :)
