### ISSUE TITLE
WHD not loading 

### ISSUE THREAD

**Issue by abrasion66** [FrodeSolheim/fs-uae-launcher#96]
I tryed many WHD that work fine with the 3.0.5 but with the current master i have an error : 

Task: RunnerTask
Error: Exception
Message: Could not install file DH0/C/SetPatch: Did not find file with SHA-1 checksum 4d4aae988310b07726329e436b2250c0f769ddff

Only for whd no problems with adf

note : if i check /tmp/fsgamesys-gkatm1bwtmp/RUN/DH0/C/SetPatch
no files are in compare to the tmp of 3.0.5

**Comment by FrodeSolheim** [comment]
Version 3.0.5 also tries to install SetPatch from a Workbench disk, but does not require it (only gives a warning if not found). The changed behavior is that right now the Launcher requires it. You can let the Launcher scan a Workbench 3.0 disk to let it find and install the SetPatch file (recommended), but I'll also add a fix to the Launcher later this evening which makes the file optional again.

**Comment by abrasion66** [comment]
okay, thanks you again for the answer to my stupiid question

**Comment by abrasion66** [comment]
Workbench 3.0 - disk 1 added to my adf directory and now it's all good, but maybe it would be good to clearly tell the user to add that disk to use whdload ?
