### ISSUE TITLE
White text on white with Linux qt5 (kvantum) dark theme

### ISSUE THREAD

**Issue by abrasion66** [FrodeSolheim/fs-uae-launcher#99]
Any of dark theme that use a white text color make the general menu white on white

**Comment by FrodeSolheim** [comment]
This is with the master branch? I could not reproduce here, but maybe it depends on how the Qt5 theme is set.

What desktop environment / Linux distro are you using?

**Comment by abrasion66** [comment]
i'm using Cinnamon on manjaro linux, any kvantum dark theme do the same and i havent do any tweak on qt5

**Comment by FrodeSolheim** [comment]
I managed to reproduce the problem, will come up with a fix :+1:

**Comment by FrodeSolheim** [comment]
Should be fixed in commit 4381209678250a0d26dca215d43fef1eebc6c246

**Comment by abrasion66** [comment]
Fixe worked for me, good work !
